### ISSUE TITLE
Game crashes when GDSAM node is in scene tree

### ISSUE THREAD

**Issue by HeroRobb** [deadpixelsociety/gdsam-plugin#1]
Whenever I run a game in the editor, it crashes with a "Attempt to call function 'new' in base 'NativeScript' on a null instance." for line 27: `onready var _gdsam = preload("res://addons/gdsam/bin/gdsam.gdns").new()`

**Comment by deadpixelsociety** [comment]
Thanks, I haven't seen this myself yet while using it.  Are you sure you have the addon in the correct directories? Does gdsam.gdns exist at the location referenced above?

Can you send me a small project that reproduces the issue? I'll be glad to take a look at it.

**Comment by vectorassembly** [comment]
Can confirm, i get the same error even with a blank project in Godot 3.4.2 on Windows 11

**Comment by deadpixelsociety** [comment]
> Can confirm, i get the same error even with a blank project in Godot 3.4.2 on Windows 11

Thank you, can you zip that project and send it over?

**Comment by deadpixelsociety** [comment]
In lieu of getting a reproduction test case, you can try updating the plugin via the asset library. There was a crash bug in the initial release with long strings that MAY be the problem you guys are encountering, but without a project I can't verify that for sure.

**Comment by HeroRobb** [comment]
Awesome! It works now. Thank you very much.

**Comment by deadpixelsociety** [comment]
> Awesome! It works now. Thank you very much.

Glad to hear it! I'll go ahead and close this out, have fun.
