### ISSUE TITLE
Error when running the example scene

### ISSUE THREAD

**Issue by mathakim29** [deadpixelsociety/gdsam-plugin#10]
Image of code, console and error
![image](https://github.com/deadpixelsociety/gdsam-plugin/assets/137667685/98ac5dbf-331b-4f4d-8e12-0c27890b2717)

**Comment by deadpixelsociety** [comment]
Hi, thanks for the report. Are you running this in a Godot 4.0 build, or a different version?

**Comment by mathakim29** [comment]
i ran it on godot 4.0.3, does it have breaking changes?

**Comment by deadpixelsociety** [comment]
> i ran it on godot 4.0.3, does it have breaking changes?

It does not, I can open and run the project without issue on 4.0.3. Sounds like you have some other issue. If you'd like you can zip up your current project and send it to me, otherwise try removing the plugin and adding it again from a clean start.

**Comment by deadpixelsociety** [comment]
Without a reproduction I am unable to doing anything on this. Closing.
