### ISSUE TITLE
Error loading GDSam on Godot 4.1

### ISSUE THREAD

**Issue by HunterTheHusky** [deadpixelsociety/gdsam-plugin#11]
### Godot reports "Error loading extension" that points to the .gdextension file.
**Stack Trace output:**
* core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/gdsam/bin/gdsam.gdextension
* Failed loading resource: res://addons/gdsam/bin/gdsam.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

**Errors when adding/loading the plugin asking for a change to the .gdextension file.**
Adding the required line in the .gdextension file "compatibility_minimum" within configuration causes my project to not open. The errors will display if files are manually added or added via the Asset Library. The project had no errors with the plugin prior to upgrade from 4.0 to 4.1.

**The issue is present with a high probability**

**Comment by deadpixelsociety** [comment]
Thanks for the report, the plugin needs to be updated to support 4.1 GDExtension changes. I have this slated, just haven't had time yet! I'll get to it this week, hopefully.

**Comment by deadpixelsociety** [comment]
@HunterTheHusky The plugin has been updated to 4.1 in this repository. Updates have been submitted to the Godot Asset Library, just pending approval.

**Comment by HunterTheHusky** [comment]
Great work, @deadpixelsociety. Thank you for the update!
