### ISSUE TITLE
help I have no idea what I'm doing

### ISSUE THREAD

**Issue by Moonteamin** [deadpixelsociety/gdsam-plugin#17]
I just want the funny robot to make noises, but instead it keeps crashing 
![image_2023-12-13_002221862](https://github.com/deadpixelsociety/gdsam-plugin/assets/141569210/ecc5302d-09ca-4a7d-b5ce-58434723c237)
![image](https://github.com/deadpixelsociety/gdsam-plugin/assets/141569210/7413e306-c505-49f6-9fdc-71cf4d10014a)

I know I'm probably fucking up but I have no idea

**Comment by deadpixelsociety** [comment]
Hello! A couple of things:

1. Change that "bufferD" back to  just "buffer".
2. You should not be extending GDSAM to utilize it. Instead in your player script grab a reference to the GDSAM node and call speak on it from there. Right now, you are overriding the _ready() function but not calling down into the base so GDSAM is not functioning correctly.

**Comment by Moonteamin** [comment]
I got it to work! Thank you so much!
