### ISSUE TITLE
Is there a way to use the sample that sam generates and modify it using sound FX?

### ISSUE THREAD

**Issue by TheBricktop** [deadpixelsociety/gdsam-plugin#2]
Im thining about a way to store the generated audio clip and modify it using audio player, how should I approach it?

**Comment by deadpixelsociety** [comment]
Hey, sorry I didn't see this sooner!

You certainly could grab the clip and mess with it. If you want to mess with it and intercept the data you would want to do it in this section:

https://github.com/deadpixelsociety/gdsam-plugin/blob/3eb58ec79aeee94d0db975085f2f7fc433d078b6/addons/gdsam/gdsam.gd#L158-L165

Here is where the phrase is generated and returned from the C code and fed into an AudioStreamSample and then to the active AudioStreamPlayer.

So I could think of a few ways you could alter this:

1. Grab the buffer data directly and do with it what you'd like.
2. Grab the existing AudioStreamPlayer (via GDSAM/AudioStreamPlayer) and utilize it.
3. Change which bus the AudioStreamPlayer utilizes and add effects directly to that bus.

**Comment by TheBricktop** [comment]
Thank You for the response,
im very much interested in modification an the humanisation of gdsam output, and seeing that not only the sam output cam be positional and might even be filtered adds so much possibilities to use this micro tts.

**Comment by deadpixelsociety** [comment]
I'll think about pushing an update this weekend to add a signal that lets you grab that raw data without having to modify the code. Stay tuned!

**Comment by deadpixelsociety** [comment]
I've updated GDSAM to provide a new signal, `buffer_loaded`, to allow you to capture the incoming buffer data, manipulate it and return an audio stream override if you wish. Checkout the [pull request](https://github.com/deadpixelsociety/gdsam-plugin/pull/3#issue-1419442096) for an example. Hopefully this does what you need!
